### ISSUE TITLE
ラジコンが左右にブレずに動くための処理追加

### ISSUE THREAD

**Issue by Dai1678** [Dai1678/ScriptArduinoRC#5]
現状、左右のモーター出力値を両方一緒にしているが、左右に大きくブレて動作している。

既知問題として、電池残量等の要因によって例えば直進であっても左右のタイヤの回転数が異なり真っ直ぐ直進しない。

左右のモーター出力値をそれぞれ設定して送信する場合、現状の処理だと送信データ量がさらに多くなり、最大送信可能命令数が減少する

**Comment by Dai1678** [comment]
@nakasatomiと@ogawaraがいい感じになんとかしてくれる

**Comment by multiverse2011** [comment]
ほぼ直ったと思われます。動作確認後closeします

**Comment by multiverse2011** [comment]
モーター側の問題＆アプリでのグローバルに設定できる項目の実装が完了したのでcloseします
